services:
  u-touch-edm:
    build: .
    container_name: u-touch-edm
    restart: always
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DB_HOST=1Panel-mysql-UHRJ
      - DB_PORT=3306
      - DB_NAME=edm-db
      - DB_READONLY_USER=edm-db
      - DB_READONLY_PASSWORD=yQQPFaTDGXBFjJWW
      - DB_APP_USER=edm-db
      - DB_APP_PASSWORD=yQQPFaTDGXBFjJWW
      - GMAIL_USER=info@uforward.jp
      - GMAIL_PASSWORD=${GMAIL_PASSWORD:-pwqltfgitutzdxro}
      - GA_TRACKING_ID=UA-172341524-1
      - TZ=Asia/Tokyo
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - default

networks:
  default:
    name: 1panel-network
    external: true
